### ISSUE TITLE
Уточнение названий полей в форме бронирования

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#10]
Первое поле называется "Имя клиента" . А если пришел директор завода "Монолит", и в честь выполнения двойного плана забронировал для всех мужиков билеты. Поле можно назвать "Клиент (Имя, организация, ... что-то еще)" 
Второе поле "контактные данные". Чтобы не возникало разночтений между кассирами (вдруг кто начнет креативить и диктовать бабушке эмеил адрес, это сильно замедлит очередь :), предлагаю добавить подсказку , что нам нужен именно номер телефона. Тоесть "Контактные данные (номер телефона) "

**Comment by Ivnst** [comment]
По большому счёту завод "монолит" - это тоже клиент. В общем, я думаю, что можно оставить названия полей без изменений. А бабушек при приёме на работу инструктировать о том, как заполнять поле "контактные данные"

**Comment by Almazik8** [comment]
ну это-же не сложно, добавить подсказочку, и сохранить инструктору нервочки ))) к тому-же бабушки бывают ооочень забывчивыми ;)
