### ISSUE TITLE
некорректное отображение алертов.

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#11]
После выполнения любого действия , окончание которого вызывает алерт(или окошко состояния, исправьте по правильной терминологии) , сначала, примерно на пол секунды, появляется алерт от прошлого законченного действия, а потом уже актуальный.  Например мы продали билет, а нам сначала показалось окошко что билеты забронированы (перед этим мы и правда бронировали) а потом окошко изменилось на правильное "операция прошла успешно"

**Comment by Ivnst** [comment]
Вроде нашёл как исправить. Проверьте, пожалуйста.
