### ISSUE TITLE
Создание стадионов (секторов) с одинаковым названием

### ISSUE THREAD

**Issue by niurochka851** [Ivnst/DATS#18]
1)Шаги воспроизведения (Steps to Reproduce): 
Открыть сайт
Перейти в настройки
Выбрать стадион(сектор)
Создать стадион(сектор)
Продублировать создание стадиона(сектора) с таким же именем
Сохранить
2)Фактический Результат (Result):
Сохраняет оба названия
3)Ожидаемый результат (Expected Result):  
Выдавать ошибку, о том что на такой стадион(сектор) уже сущестует

**Comment by sekonungr** [comment]
Решили, что такое вполне может быть - в разных города стадион "Динамо", регистрировать или нет это уже дело пользователя.

**Comment by niurochka851** [comment]
Да но когда создаешь стадион с одним и тем же названием и адресом,ну как-то вообще ...."ирония судьбы"))
