### ISSUE TITLE
При введении значения «invalid» в поля настроек, кнопка «Закрыть» не работает

### ISSUE THREAD

**Issue by niurochka851** [Ivnst/DATS#19]
1)Шаги воспроизведения (Steps to Reproduce): 
Открыть сайт
Перейти в настройки
Выбрать мероприятие 
Нажать edit
Ввести отрицательную цену
Нажать «закрыть»
2)Фактический Результат (Result)    :
Не работает кнопка, приходится нажимать возвращаться к исходному  виду нажатием backspace многократно
3)Ожидаемый результат (Expected Result)  
Закрыть страницу не сохраняя

**Comment by sekonungr** [comment]
Исправлено, правда позже поле реализации валидации на лету в этот режим броузер попадать уже не будет.

**Comment by niurochka851** [comment]
При бронировании если че-то там не ввел то кнопка тоже не закрывает

**Comment by sekonungr** [comment]
От предыдущего исправления отказались, так как оно конфликтовало с проверкой jQuery Validation Plugin. Теперь форма вообще не выходит из модального режима (за исключением поля "Дата и время начала" в Мероприятиях, реализация проверки которого будет добавлена уже после внедрения календаря).
