### ISSUE TITLE
Ограничить продолжительность матча до реального значения 

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#29]
![2014-07-22 21_29_07-mozilla firefox](https://cloud.githubusercontent.com/assets/8185328/3662960/13b910c0-11cf-11e4-8335-fd9bdcb053c6.png)
Спросила в скайпе у заказчика максимально возможную продолжительность матча, обновлю тикет когда получу ответ

**Comment by sekonungr** [comment]
Так как мероприятия могут пересекаться между собой, то установка сколь-угодно большого допустимого значения к негативным последствиям не приведет, а пользователю может пригодится в каких то случаях возможность установки большего значения (например, некое длительное мероприятие с абонементом) без обращения в службу поддержки.
