### ISSUE TITLE
Добовить подсказку возле поля поиска по бронированию

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#31]
Нужна подсказка возле  поля поиска по брони на странице "забронированные билеты" . Подсказка должна сообщать по каким значениям ведется поиск. Типа " Введите номер брони или данные клиента (имя, контактные данные) которые он сообщал при бронировании

**Comment by Ivnst** [comment]
Добавил всплывающую при наведении на текстовое поле
