### ISSUE TITLE
ошибка при вводе неккоректной даты в окне создания мероприятия

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#34]
![2014-07-22 19_47_45-mozilla firefox](https://cloud.githubusercontent.com/assets/8185328/3663434/0394ccd0-11d3-11e4-8ea8-518db94f4756.jpg)

**Comment by sekonungr** [comment]
Исправлена,  написан пользовательский анализатор даты, который выполняет те же проверки, что и аннотация данных модели, предотвращая переход из модального окна в эту форму.
