### ISSUE TITLE
кнопочка fit to size

### ISSUE THREAD

**Issue by niurochka851** [Ivnst/DATS#37]
Неплохо было бы кнопочку  fit to size возле увеличения и уменьшения масштаба,чтобы возвращаться к привычному масштабу

**Comment by Almazik8** [comment]
на какой страничке? Редактирование секторов? там зум ограничили, так что кликать назад совсем не много ))

**Comment by niurochka851** [comment]
на страничке продаж,и это было как предложение))зууум вижу

**Comment by Ivnst** [comment]
Сделал кнопку, которая выбирает оптимальный масштаб. И он же выбирается по умолчанию.
