### ISSUE TITLE
запретить ввод отрицательного значения в конфигурации

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#44]
![2014-07-27 03_06_30-](https://cloud.githubusercontent.com/assets/8185328/3712639/60c6c24a-1526-11e4-8035-a1e7a5c33804.png)
![2014-07-27 03_36_58-](https://cloud.githubusercontent.com/assets/8185328/3712640/66dd417c-1526-11e4-98db-66ccd9a669c4.png)

разрешает ввод отрицательного значения в поле настроек возврата забронированных билетов в продажу (настройки - конфигурация) это дает возможность совершать операцию бронирования  билетов после начала мароприятия.

**Comment by sekonungr** [comment]
Добавил эту проверку перед сохранением.
