### ISSUE TITLE
В поиске отображается старая бронь на прошедшие мероприятия 

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#45]
В поиске отображается старая бронь на прошедшие мероприятия , билеты можно продать и вернуть в продажу. 
![2014-07-27 04_12_58-](https://cloud.githubusercontent.com/assets/8185328/3712699/67498b66-152b-11e4-9e77-3d4f048b09fe.png)

**Comment by Ivnst** [comment]
Это дата бронирования. Бронь за прошедшие мероприятия не может существовать, так как она будет сниматься за полчаса до начала.
