### ISSUE TITLE
название сектора длиной менее 255,выходит за рамки  окна подсказки

### ISSUE THREAD

**Issue by niurochka851** [Ivnst/DATS#48]
Название менее 255,но длинное  при сохранении выходит за рамки окна подсказки о том что сектор успешно сохранен

**Comment by Ivnst** [comment]
На счёт названий, предложите оптимальную длину для назавний и других полей. Чтобы никуда не выходило.

**Comment by Almazik8** [comment]
![2014-07-27 15_21_53-](https://cloud.githubusercontent.com/assets/8185328/3713871/b1e516ba-1588-11e4-808a-1d460ea3c8a8.png)
пришли другой скриншот где видно что название выходит за рамки

**Comment by Almazik8** [comment]
а насчет длинны- с ограничением в 255 пока ничего не ломает, а потом заказчик сам скажет сколько ему нужно символов и в каких полях

**Comment by niurochka851** [comment]
это не принципиально,как предложение))
http://i67.fastpic.ru/big/2014/0727/8f/c49b73d0889c97fb2a809217ab9fa28f.png

**Comment by Almazik8** [comment]
![2014-07-27 16_23_37-](https://cloud.githubusercontent.com/assets/8185328/3714027/9d954e38-1591-11e4-9aa5-c016988564ef.png)
Ага, оно репродьюсится если слово слишком длинное, нету пробелов, не срабатывает перенос и строка вылезает за рамки

**Comment by sekonungr** [comment]
Ещё нужно учесть, что слова которые пишутся слитно обычно не превышают 30 символов, а следовательно текст будет переносится на другие строки. Т.е. нет смысла ограничивать размер текстового поля менее 255.

**Comment by Almazik8** [comment]
превышают_или_не_превышают_а_вот_у_меня_не_работает_пробел,_например._И_я_пишу_как_могу._Что_тогда?_В_любом_случае_текст_за_рамки_выходить_не_должен,_независимо_от_того_есть_такое_слово_или_нету._Гит_же_вот_переносит)))_Не_надо_надеяться_на_благоразумие_пользователей._Закрывать_надо_все_уязвимости;)

**Comment by Almazik8** [comment]
странно реагирует гит, я писала все через нижнее подчеркивание _ _

**Comment by Ivnst** [comment]
Это не странное рагирование, это что-то наподобие _wiki_ **разметки**)

**Comment by Ivnst** [comment]
Во-вторых, если у админа сломался пробел, то это плохой админ)

**Comment by Ivnst** [comment]
В-третьих, это не уязвимость. На безопасность сайта это никак не влияет. Просто сайту не удаётся отобразить некоторые элементы корректным образом.
