### ISSUE TITLE
<script> </script> так и копируется во все поля 

### ISSUE THREAD

**Issue by niurochka851** [Ivnst/DATS#49]
Вызывает Runtime Error

**Comment by niurochka851** [comment]
копируется в поля  поиска по брони,название секторов и мероприятий

**Comment by sekonungr** [comment]
Нет, смысла заменять эту ошибку на цивилизованный интерфейс нотификации, если пользователь предпринимает злонамеренные действия, то важно, чтобы эти действия не привели к исполнению скрипта - сейчас так оно и есть и совсем не важно какое при этом увидит сообщение пользователь. Вполне логично, что сайт отказывает в дальнейшем обслуживании такого пользователя. Конечно, логирование таких случаев желательно будет привинтить.

**Comment by Ivnst** [comment]
Запретил ввод угловых скобок в поля с названиями (стадионов, секторов и тд). Поэтому этой ошибки больше возникать не должно.
