### ISSUE TITLE
Создание мероприятий на одно и тоже время

### ISSUE THREAD

**Issue by niurochka851** [Ivnst/DATS#5]
1) Шаги воспроизведения (Steps to Reproduce) 
Открыть сайт
Перейти в настройки
Выбрать стадион
Выбрать поле Мероприятия
Создать 2 разных мероприятия на одно и тоже время
Сохранить
2) Фактический Результат (Result)-Сохраняет оба мероприятия
3) Ожидаемый результат (Expected Result)-Выдавать ошибку, о том что на данное время уже есть мероприятие.

**Comment by sekonungr** [comment]
Решили, что такое поведение багом не является, так как в общем случае в принципе может быть.

**Comment by niurochka851** [comment]
а если речь идет о какой-то накладке,там типа две сотрудника случайно заводят одно и тоже мероприятие?
