### ISSUE TITLE
Изменить текст  подсказкок в окне авторизации

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#52]
переписать подсказки в окне авторизации на интуитивно понятные для пользователя 
![2014-08-02 16_56_41-mozilla firefox](https://cloud.githubusercontent.com/assets/8185328/3788071/083fe230-1a50-11e4-9f87-44159af196b4.png)

**Comment by sekonungr** [comment]
Исправил, в ветке для слияния с релизом этот баг уже учтен.
