### ISSUE TITLE
Поле «Выбрано мест:» на странице продажи не обновляется

### ISSUE THREAD

**Issue by niurochka851** [Ivnst/DATS#6]
1)Шаги воспроизведения (Steps to Reproduce):
Открыть сайт
Выбрать мероприятие
Выбрать сектор
Выбрать места нажать продать
Выделить те же места нажать возврат
2)Фактический Результат (Result):
Поле «Выбрано мест» сохраняет кол-во проданных мест и не обнуляется после возврата
3)Ожидаемый результат (Expected Result):
Поле «Выбрано мест» обнулено после возврата

**Comment by Ivnst** [comment]
Исправлено
