### ISSUE TITLE
Ошибка при одновременной продаже с двух одинаковых страниц 

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#7]
![2014-07-17 02_49_30-](https://cloud.githubusercontent.com/assets/8185328/3607293/65c2f662-0d45-11e4-8670-d7fc13ed8860.jpg)

При попытке продажи одних и тех же мест на определенное событие одного стадиона валидно срабатывает очередность покупки, но появляется ошибка в окне где операция была совершена позже.

**Comment by Ivnst** [comment]
Не могу воспроизвести
