### ISSUE TITLE
Подсказки в окне бронирования 

### ISSUE THREAD

**Issue by Almazik8** [Ivnst/DATS#9]
1. Насколько целесообразны выпадающие подсказки в окне бронирования ? Также стоит заметить, что для всех стадионов и мероприятий они общие, тоесть очень скоро вырастут в длиннющий список . предлагаю их убрать. Отпишите в комментах кто что думает по этому поводу.

**Comment by Ivnst** [comment]
Проверил дома - браузер ничего не подсказывает. Видимо от настроек зависит.

**Comment by Ivnst** [comment]
Кстати, нашёл как убрать это. Скоро исправлю

**Comment by Ivnst** [comment]
Убрал
